import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

const SUPABASE_URL='https://dvvaymfuzprxqxfoqtzo.supabase.co';
const SUPABASE_KEY='sb_publishable_CqNqbc_2Vx-YnTPw_h5A3g_Ai1kmuRk';
const SPACE_ID='11111111-1111-4111-8111-111111111111';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const views={login:$('#loginView'),home:$('#homeView'),admin:$('#adminView')};
const toast=msg=>{const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)};
function show(name){Object.values(views).forEach(v=>v.classList.remove('active'));views[name].classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function calcDays(date='2024-02-14'){const d=Math.max(0,Math.floor((new Date()-new Date(date))/(864e5)));$('#daysTogether').textContent=d}
const defaults={name:'心动空间',width:1180,font:16,opacity:78,blur:18,radius:28,loginTitle:'心动空间',date:'2024-02-14',hero:'和你一起，把日子过成喜欢的样子。'};
let settings={...defaults}, currentUser=null, membership=null, channel=null, isOwner=false, spaceState=null;
function apply(){document.documentElement.style.setProperty('--max',settings.width+'px');document.documentElement.style.setProperty('--base',settings.font+'px');document.documentElement.style.setProperty('--glass',settings.opacity/100);document.documentElement.style.setProperty('--blur',settings.blur+'px');document.documentElement.style.setProperty('--radius',settings.radius+'px');$('#siteName').textContent=settings.name;$('#setName').value=settings.name;$('#loginTitle').textContent=settings.loginTitle;$('#setLoginTitle').value=settings.loginTitle;$('#setDate').value=settings.date;$('#setHeroText').value=settings.hero;$('#homeView .home-copy h2').innerHTML=settings.hero.replace('，','，<br>');$('#setWidth').value=settings.width;$('#setFont').value=settings.font;$('#setOpacity').value=settings.opacity;$('#setBlur').value=settings.blur;$('#setRadius').value=settings.radius;updateOut();calcDays(settings.date)}
function updateOut(){$('#widthOut').value=$('#setWidth').value+' px';$('#fontOut').value=$('#setFont').value+' px';$('#opacityOut').value=$('#setOpacity').value+'%';$('#blurOut').value=$('#setBlur').value+' px';$('#radiusOut').value=$('#setRadius').value+' px'}
['setWidth','setFont','setOpacity','setBlur','setRadius'].forEach(id=>$('#'+id).addEventListener('input',updateOut));

async function ensureMember(user,nickname='恋人'){
  const {data}=await supabase.from('ls_members').select('*').eq('user_id',user.id).eq('space_id',SPACE_ID).maybeSingle();
  if(data){membership=data;return}
  const name=nickname.trim()||user.email?.split('@')[0]||'恋人';
  const {data:joined,error}=await supabase.from('ls_members').insert({space_id:SPACE_ID,user_id:user.id,nickname:name,role:'member'}).select().single();
  if(error) throw error; membership=joined;
  const {data:space}=await supabase.from('ls_spaces').select('owner_id').eq('id',SPACE_ID).single();
  if(!space?.owner_id){await supabase.from('ls_spaces').update({owner_id:user.id}).eq('id',SPACE_ID);membership.role='owner'}
}
async function loadSettings(){
  const {data}=await supabase.from('ls_settings').select('*').eq('space_id',SPACE_ID).maybeSingle();
  if(data) settings={...defaults,name:data.name,start_date:data.start_date,date:data.start_date,hero:data.hero_text,loginTitle:data.login_title,width:data.width,font:data.font,opacity:data.opacity,blur:data.blur,radius:data.radius};
  apply();
  if(data){$('#toggleMessage').checked=data.messages_enabled!==false;$('#toggleGallery').checked=data.gallery_enabled!==false;$('#toggleMoments').checked=data.moments_enabled!==false;document.querySelector('.message-box').closest('.content-section').style.display=data.messages_enabled===false?'none':'';$('#gallery').style.display=data.gallery_enabled===false?'none':'';$('#moments').style.display=data.moments_enabled===false?'none':''}
  if(data?.login_image_path) await setPrivateBg($('#loginHero'),data.login_image_path);
  if(data?.hero_image_path) await setPrivateBg($('#homeHero'),data.hero_image_path);
}
async function setPrivateBg(el,path){const {data,error}=await supabase.storage.from('couple-media').createSignedUrl(path,3600);if(!error)el.style.backgroundImage=`linear-gradient(rgba(0,0,0,.1),rgba(0,0,0,.18)),url('${data.signedUrl}')`}
async function enterApp(user,nickname=''){currentUser=user;await ensureMember(user,nickname);await loadOwnerState();if(membership?.status==='frozen'&&!isOwner){await supabase.auth.signOut();currentUser=null;membership=null;show('login');return toast('此账号已被最高权限冻结')}if((spaceState?.maintenance_mode||spaceState?.site_locked)&&!isOwner){show('login');return toast(spaceState.site_locked?'空间已被最高权限锁定':'空间维护中，请稍后再来')}await Promise.all([loadSettings(),loadMessages(),loadPhotos()]);subscribe();show('home');toast('欢迎回来 ♡')}

$('#loginBtn').onclick=async()=>{try{const email=$('#account').value.trim(),password=$('#password').value;const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await enterApp(data.user)}catch(e){toast('登录失败：'+e.message)}};
$('#registerBtn').onclick=async()=>{try{const email=$('#account').value.trim(),password=$('#password').value,nickname=$('#nickname').value.trim();if(!nickname)return toast('请先填写昵称');const {data,error}=await supabase.auth.signUp({email,password,options:{data:{nickname}}});if(error)throw error;if(!data.session)return toast('注册成功，请先到邮箱完成验证');await enterApp(data.user,nickname)}catch(e){toast('注册失败：'+e.message)}};
$('#logoutBtn').onclick=async()=>{await supabase.auth.signOut();currentUser=null;membership=null;if(channel)supabase.removeChannel(channel);show('login');toast('已退出登录')};
$('#openAdmin').onclick=()=>currentUser?show('admin'):toast('请先登录');$('#homeAdmin').onclick=()=>show('admin');$('#backSite').onclick=()=>show('home');
$$('[data-scroll]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
$$('.tab').forEach(btn=>btn.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');$$('.panel').forEach(x=>x.classList.remove('active'));$(`[data-panel="${btn.dataset.tab}"]`).classList.add('active');$('#panelTitle').textContent=btn.textContent});

async function saveSettings(patch){if(!currentUser)return;const payload={name:settings.name,start_date:settings.date,hero_text:settings.hero,login_title:settings.loginTitle,width:settings.width,font:settings.font,opacity:settings.opacity,blur:settings.blur,radius:settings.radius,...patch,updated_at:new Date().toISOString()};const {error}=await supabase.from('ls_settings').update(payload).eq('space_id',SPACE_ID);if(error)throw error}
$('#saveLayout').onclick=async()=>{try{settings={...settings,name:$('#setName').value||'心动空间',width:+$('#setWidth').value,font:+$('#setFont').value,opacity:+$('#setOpacity').value,blur:+$('#setBlur').value,radius:+$('#setRadius').value};await saveSettings({});apply();toast('布局已同步到云端')}catch(e){toast('保存失败：仅空间创建者可修改')}};
$('#savePage').onclick=async()=>{try{settings={...settings,loginTitle:$('#setLoginTitle').value||'心动空间',date:$('#setDate').value||'2024-02-14',hero:$('#setHeroText').value||defaults.hero};await saveSettings({});apply();toast('页面内容已同步')}catch(e){toast('保存失败：仅空间创建者可修改')}};

async function uploadFile(file,kind){if(!currentUser||!file)return null;if(file.size>10*1024*1024)throw new Error('图片不能超过 10MB');const ext=(file.name.split('.').pop()||'jpg').replace(/[^a-z0-9]/gi,'');const path=`${SPACE_ID}/${currentUser.id}/${kind}-${Date.now()}.${ext}`;const {error}=await supabase.storage.from('couple-media').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;return path}
async function bindCoverUpload(input,target,column){input.onchange=async()=>{try{const path=await uploadFile(input.files[0],column);const {error}=await supabase.from('ls_settings').update({[column]:path,updated_at:new Date().toISOString()}).eq('space_id',SPACE_ID);if(error)throw error;await setPrivateBg(target,path);toast('图片已上传并同步')}catch(e){toast('上传失败：'+e.message)}}}
bindCoverUpload($('#loginUpload'),$('#loginHero'),'login_image_path');bindCoverUpload($('#homeUpload'),$('#homeHero'),'hero_image_path');

async function loadMessages(){const {data,error}=await supabase.from('ls_messages').select('*').eq('space_id',SPACE_ID).order('created_at',{ascending:true}).limit(100);if(error)return;const box=$('#messages');box.innerHTML='';(data||[]).forEach(renderMessage);if(!data?.length)box.innerHTML='<p class="muted">还没有悄悄话，写下第一句吧 ♡</p>';box.scrollTop=box.scrollHeight}
function renderMessage(m){const box=$('#messages');if(box.querySelector('.muted'))box.innerHTML='';const p=document.createElement('p'),b=document.createElement('b');b.textContent=(m.nickname||'恋人')+'：';p.append(b,document.createTextNode(' '+m.body));box.appendChild(p);box.scrollTop=box.scrollHeight}
$('#sendMessage').onclick=async()=>{const body=$('#messageInput').value.trim();if(!body||!currentUser)return;const {error}=await supabase.from('ls_messages').insert({space_id:SPACE_ID,user_id:currentUser.id,nickname:membership?.nickname||'恋人',body});if(error)return toast('发送失败：'+error.message);$('#messageInput').value=''};
$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendMessage').click()});

async function loadPhotos(){const {data,error}=await supabase.from('ls_photos').select('*').eq('space_id',SPACE_ID).order('created_at',{ascending:false}).limit(30);if(error)return;const grid=$('#photoGrid');grid.innerHTML='';for(const p of data||[]){const {data:s}=await supabase.storage.from('couple-media').createSignedUrl(p.storage_path,3600);if(!s)continue;const d=document.createElement('div');d.className='photo';d.style.backgroundImage=`url('${s.signedUrl}')`;const cap=document.createElement('span');cap.textContent=p.caption||'共同回忆';d.appendChild(cap);grid.appendChild(d)}if(!data?.length)grid.innerHTML='<p class="muted">还没有云端照片，上传第一张吧。</p>'}
$('#galleryUpload').onchange=async()=>{try{const file=$('#galleryUpload').files[0];const path=await uploadFile(file,'gallery');const {error}=await supabase.from('ls_photos').insert({space_id:SPACE_ID,user_id:currentUser.id,storage_path:path,caption:file.name});if(error)throw error;toast('照片已上传')}catch(e){toast('上传失败：'+e.message)}};
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('love-space-'+SPACE_ID).on('postgres_changes',{event:'INSERT',schema:'public',table:'ls_messages',filter:`space_id=eq.${SPACE_ID}`},p=>renderMessage(p.new)).on('postgres_changes',{event:'INSERT',schema:'public',table:'ls_photos',filter:`space_id=eq.${SPACE_ID}`},()=>loadPhotos()).subscribe()}

async function saveFeatureToggle(column,value){if(!isOwner){toast('仅最高权限可修改全站功能');await loadSettings();return}const {error}=await supabase.from('ls_settings').update({[column]:value,updated_at:new Date().toISOString()}).eq('space_id',SPACE_ID);if(error)return toast('保存失败：'+error.message);toast('功能开关已同步')}
$('#toggleMessage').onchange=e=>{document.querySelector('.message-box').closest('.content-section').style.display=e.target.checked?'':'none';saveFeatureToggle('messages_enabled',e.target.checked)};$('#toggleGallery').onchange=e=>{$('#gallery').style.display=e.target.checked?'':'none';saveFeatureToggle('gallery_enabled',e.target.checked)};$('#toggleMoments').onchange=e=>{$('#moments').style.display=e.target.checked?'':'none';saveFeatureToggle('moments_enabled',e.target.checked)};
$('#resetAll').onclick=async()=>{try{settings={...defaults};await saveSettings({});apply();toast('已恢复默认设置')}catch(e){toast('恢复失败：仅空间创建者可操作')}};


async function loadOwnerState(){
  const {data,error}=await supabase.from('ls_spaces').select('owner_id,maintenance_mode,site_locked').eq('id',SPACE_ID).single();
  if(error)throw error; spaceState=data; isOwner=data?.owner_id===currentUser?.id;
  $$('.super-only').forEach(el=>el.style.display=isOwner?'':'none');
  if(isOwner){$('#maintenanceMode').checked=!!data.maintenance_mode;$('#siteLocked').checked=!!data.site_locked;$('#superState').textContent=data.site_locked?'已锁定':data.maintenance_mode?'维护中':'正常运行'}
}
async function audit(action,targetType='system',targetId=null,details={}){if(!isOwner)return;await supabase.from('ls_audit_logs').insert({space_id:SPACE_ID,actor_id:currentUser.id,action,target_type:targetType,target_id:targetId,details})}
async function loadMembers(){if(!isOwner)return;const {data,error}=await supabase.from('ls_members').select('user_id,nickname,role,status,joined_at').eq('space_id',SPACE_ID).order('joined_at');const box=$('#memberAdmin');if(error){box.textContent='读取失败：'+error.message;return}box.innerHTML='';for(const m of data||[]){const row=document.createElement('div');row.className='member-row';const info=document.createElement('div');const b=document.createElement('b');b.textContent=m.nickname||'恋人';if(m.user_id===spaceState.owner_id){const badge=document.createElement('span');badge.className='owner-badge';badge.textContent='最高权限';b.appendChild(badge)}const small=document.createElement('small');small.textContent=(m.status==='frozen'?'已冻结':'正常')+' · '+new Date(m.joined_at).toLocaleDateString();info.append(b,small);row.append(info);if(m.user_id!==spaceState.owner_id){const actions=document.createElement('div');actions.className='member-actions';const freeze=document.createElement('button');freeze.className='freeze';freeze.textContent=m.status==='frozen'?'解除冻结':'冻结';freeze.onclick=()=>setMemberStatus(m,m.status==='frozen'?'active':'frozen');const remove=document.createElement('button');remove.className='remove';remove.textContent='移出空间';remove.onclick=()=>removeMember(m);actions.append(freeze,remove);row.append(actions)}box.append(row)}
}
async function setMemberStatus(m,status){if(!isOwner)return;if(!confirm(`${status==='frozen'?'冻结':'解除冻结'}成员「${m.nickname}」？`))return;const {error}=await supabase.from('ls_members').update({status,updated_at:new Date().toISOString()}).eq('space_id',SPACE_ID).eq('user_id',m.user_id);if(error)return toast('操作失败：'+error.message);await audit(status==='frozen'?'freeze_member':'unfreeze_member','member',m.user_id,{nickname:m.nickname});toast('成员状态已更新');await Promise.all([loadMembers(),loadAuditLogs()])}
async function removeMember(m){if(!isOwner||!confirm(`确认将「${m.nickname}」移出当前空间？此操作不会删除其 Supabase Auth 账号。`))return;const {error}=await supabase.from('ls_members').delete().eq('space_id',SPACE_ID).eq('user_id',m.user_id);if(error)return toast('移出失败：'+error.message);await audit('remove_member','member',m.user_id,{nickname:m.nickname});toast('已移出空间');await Promise.all([loadMembers(),loadAuditLogs()])}
async function loadAuditLogs(){if(!isOwner)return;const {data}=await supabase.from('ls_audit_logs').select('action,target_type,target_id,details,created_at').eq('space_id',SPACE_ID).order('created_at',{ascending:false}).limit(50);const box=$('#auditLogs');box.innerHTML='';for(const x of data||[]){const d=document.createElement('div');d.className='audit-item';const label={freeze_member:'冻结成员',unfreeze_member:'解除冻结',remove_member:'移出成员',maintenance_on:'开启维护模式',maintenance_off:'关闭维护模式',lock_on:'锁定空间',lock_off:'解除锁定',clear_messages:'清空悄悄话',clear_photos:'清空照片'}[x.action]||x.action;d.textContent=label;const sm=document.createElement('small');sm.textContent=new Date(x.created_at).toLocaleString();d.append(sm);box.append(d)}if(!data?.length)box.innerHTML='<p class="muted">暂无审计记录</p>'}
async function setSpaceFlag(column,value){if(!isOwner)return;const {error}=await supabase.from('ls_spaces').update({[column]:value,updated_at:new Date().toISOString()}).eq('id',SPACE_ID);if(error)return toast('操作失败：'+error.message);spaceState[column]=value;$('#superState').textContent=spaceState.site_locked?'已锁定':spaceState.maintenance_mode?'维护中':'正常运行';await audit(column==='maintenance_mode'?(value?'maintenance_on':'maintenance_off'):(value?'lock_on':'lock_off'));await loadAuditLogs();toast('最高权限设置已生效')}
$('#maintenanceMode').onchange=e=>setSpaceFlag('maintenance_mode',e.target.checked);$('#siteLocked').onchange=e=>setSpaceFlag('site_locked',e.target.checked);
$('#clearMessages').onclick=async()=>{if(!isOwner||!confirm('确认清空全部悄悄话？此操作不可撤销。'))return;const {error}=await supabase.from('ls_messages').delete().eq('space_id',SPACE_ID);if(error)return toast('清理失败：'+error.message);await audit('clear_messages');await loadMessages();await loadAuditLogs();toast('全部悄悄话已清空')};
$('#clearPhotos').onclick=async()=>{if(!isOwner||!confirm('确认清空全部照片？数据库记录和云端图片都会删除，且不可撤销。'))return;const {data,error}=await supabase.from('ls_photos').select('storage_path').eq('space_id',SPACE_ID);if(error)return toast('读取照片失败');const paths=(data||[]).map(x=>x.storage_path);if(paths.length){const {error:se}=await supabase.storage.from('couple-media').remove(paths);if(se)return toast('云端图片清理失败：'+se.message)}const {error:de}=await supabase.from('ls_photos').delete().eq('space_id',SPACE_ID);if(de)return toast('记录清理失败：'+de.message);await audit('clear_photos','photo',null,{count:paths.length});await loadPhotos();await loadAuditLogs();toast('全部照片已清空')};
const oldOpenAdmin=$('#openAdmin').onclick;$('#openAdmin').onclick=async()=>{if(!currentUser)return toast('请先登录');show('admin');if(isOwner)await Promise.all([loadMembers(),loadAuditLogs()])};$('#homeAdmin').onclick=async()=>{show('admin');if(isOwner)await Promise.all([loadMembers(),loadAuditLogs()])};

apply();
const {data:{session}}=await supabase.auth.getSession();if(session?.user){try{await enterApp(session.user,session.user.user_metadata?.nickname||'')}catch(e){toast('初始化失败：'+e.message);show('login')}}
